---
title: "Hypothesis_Testing"
author: "Ashlyn Jew"
date: "5/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##
```{r}
crime <- read.csv("CrimeLA_Clean.csv")
crime$Date_Rptd <- as.Date(crime$Date_Rptd)
crime$Date_Occ <- as.Date(crime$Date_Occ)
crime
```

```{r}
library(tidyverse)
crime_chinese <- crime %>% filter(Vict_Descent == "C")
crime_chinese
```

```{r}
library(lubridate)
crime_chinese %>%
  group_by(year(Date_Occ), Crm_Desc) %>%
  summarise(
    n = n()
  ) %>% 
  arrange(desc(n))
```

```{r}
# A - Other Asian B - Black C - Chinese D - Cambodian F - Filipino G - Guamanian H - Hispanic/Latin/Mexican I - American Indian/Alaskan Native J - Japanese K - Korean L - Laotian O - Other P - Pacific Islander S - Samoan U - Hawaiian V - Vietnamese W - White X - Unknown Z - Asian Indian

asian_code <- c("A", "D", "F", "J", "K", "V", "Z")

crime_asian <- crime %>% filter(Vict_Descent %in% asian_code)

crime_asian %>% 
  group_by(Vict_Descent) %>% 
  summarise(
    n = n()
  ) %>% 
  arrange(desc(n))

crime_asian %>% 
  filter(Vict_Descent == "K", year(Date_Occ) == 2019) %>% 
  group_by(Crm_Desc) %>%
  summarise(
    n = n()
  ) %>% 
  arrange(desc(n))

crime_asian %>% 
  filter(Vict_Descent == "K", month(Date_Occ) %in% c(1, 2, 3, 4, 5), year(Date_Occ) == 2019) %>% 
  group_by(year(Date_Occ), month(Date_Occ), Crm_Desc) %>%
  summarise(
    n = n()
  ) %>% 
  arrange(desc(n)) %>% 
  top_n(5)

crime_asian %>% 
  filter(Vict_Descent == "K", month(Date_Occ) %in% c(1, 2, 3, 4, 5), year(Date_Occ) == 2020) %>% 
  group_by(year(Date_Occ), month(Date_Occ), Crm_Desc) %>%
  summarise(
    n = n()
  ) %>% 
  arrange(desc(n)) %>% 
  top_n(5)
```

Who are we categorizing as Asians?
